version: "3"

services:
  react-hot-reload-starter:
    build: .
    restart: always
    stdin_open: true
    volumes:
      - ./nginx.tmpl:/etc/nginx/nginx.tmpl
    environment:
      - UPSTREAM=docker.for.mac.localhost:8080
    ports:
      - "3000:3000"
